name: factor-portfolio
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.21.0
  - pandas>=1.3.0
  - yfinance>=0.1.70
  - scikit-learn>=0.24.2
  - matplotlib>=3.4.2
  - seaborn>=0.11.1
  - cvxpy>=1.1.7 