-- Balance sheet growth
CREATE TABLE IF NOT EXISTS balance_sheet_growth (
    symbol TEXT,
    date TEXT,
    fiscal_year TEXT,
    period TEXT,
    reported_currency TEXT,

    cash_and_cash_equivalents REAL,
    short_term_investments REAL,
    cash_and_short_term_investments REAL,
    net_receivables REAL,
    inventory REAL,
    other_current_assets REAL,
    total_current_assets REAL,
    property_plant_equipment_net REAL,
    goodwill REAL,
    intangible_assets REAL,
    goodwill_and_intangible_assets REAL,
    long_term_investments REAL,
    tax_assets REAL,
    other_non_current_assets REAL,
    total_non_current_assets REAL,
    other_assets REAL,
    total_assets REAL,

    account_payables REAL,
    short_term_debt REAL,
    tax_payables REAL,
    deferred_revenue REAL,
    other_current_liabilities REAL,
    total_current_liabilities REAL,
    long_term_debt REAL,
    deferred_revenue_non_current REAL,
    deferred_tax_liabilities_non_current REAL,
    other_non_current_liabilities REAL,
    total_non_current_liabilities REAL,
    other_liabilities REAL,
    total_liabilities REAL,

    preferred_stock REAL,
    common_stock REAL,
    retained_earnings REAL,
    accumulated_other_comprehensive_income_loss REAL,
    other_total_stockholders_equity REAL,
    total_stockholders_equity REAL,
    minority_interest REAL,
    total_equity REAL,
    total_liabilities_and_stockholders_equity REAL,

    total_investments REAL,
    total_debt REAL,
    net_debt REAL,
    accounts_receivables REAL,
    other_receivables REAL,
    prepaids REAL,
    total_payables REAL,
    other_payables REAL,
    accrued_expenses REAL,
    capital_lease_obligations_current REAL,
    additional_paid_in_capital REAL,
    treasury_stock REAL,

    PRIMARY KEY (symbol, date, reported_currency),
    FOREIGN KEY (symbol) REFERENCES stocks(symbol)
);