-- Balance sheet growth
CREATE TABLE balance_sheet_growth (
    symbol TEXT,
    date TEXT,
    fiscal_year TEXT,
    period TEXT,
    reported_currency TEXT,

    growth_cash_and_cash_equivalents REAL,
    growth_short_term_investments REAL,
    growth_cash_and_short_term_investments REAL,
    growth_net_receivables REAL,
    growth_inventory REAL,
    growth_other_current_assets REAL,
    growth_total_current_assets REAL,
    growth_property_plant_equipment_net REAL,
    growth_goodwill REAL,
    growth_intangible_assets REAL,
    growth_goodwill_and_intangible_assets REAL,
    growth_long_term_investments REAL,
    growth_tax_assets REAL,
    growth_other_non_current_assets REAL,
    growth_total_non_current_assets REAL,
    growth_other_assets REAL,
    growth_total_assets REAL,

    growth_account_payables REAL,
    growth_short_term_debt REAL,
    growth_tax_payables REAL,
    growth_deferred_revenue REAL,
    growth_other_current_liabilities REAL,
    growth_total_current_liabilities REAL,
    growth_long_term_debt REAL,
    growth_deferred_revenue_non_current REAL,
    growth_deferred_tax_liabilities_non_current REAL,
    growth_other_non_current_liabilities REAL,
    growth_total_non_current_liabilities REAL,
    growth_other_liabilities REAL,
    growth_total_liabilities REAL,

    growth_preferred_stock REAL,
    growth_common_stock REAL,
    growth_retained_earnings REAL,
    growth_accumulated_other_comprehensive_income_loss REAL,
    growth_other_total_stockholders_equity REAL,
    growth_total_stockholders_equity REAL,
    growth_minority_interest REAL,
    growth_total_equity REAL,
    growth_total_liabilities_and_stockholders_equity REAL,

    growth_total_investments REAL,
    growth_total_debt REAL,
    growth_net_debt REAL,
    growth_accounts_receivables REAL,
    growth_other_receivables REAL,
    growth_prepaids REAL,
    growth_total_payables REAL,
    growth_other_payables REAL,
    growth_accrued_expenses REAL,
    growth_capital_lease_obligations_current REAL,
    growth_additional_paid_in_capital REAL,
    growth_treasury_stock REAL,

    PRIMARY KEY (symbol, date),
    FOREIGN KEY (symbol) REFERENCES stocks(symbol)
);