-- Income statement growth
CREATE TABLE IF NOT EXISTS income_statement_growth (
    symbol TEXT,
    date TEXT,
    fiscal_year TEXT,
    period TEXT,
    reported_currency TEXT,

    revenue REAL,
    cost_of_revenue REAL,
    gross_profit REAL,
    gross_profit_ratio REAL,
    research_and_development_expenses REAL,
    general_and_administrative_expenses REAL,
    selling_and_marketing_expenses REAL,
    other_expenses REAL,
    operating_expenses REAL,
    cost_and_expenses REAL,
    interest_income REAL,
    interest_expense REAL,
    depreciation_and_amortization REAL,
    ebitda REAL,
    operating_income REAL,
    income_before_tax REAL,
    income_tax_expense REAL,
    net_income REAL,
    eps REAL,
    eps_diluted REAL,
    weighted_average_shs_out REAL,
    weighted_average_shs_out_dil REAL,
    ebit REAL,
    non_operating_income_excluding_interest REAL,
    net_interest_income REAL,
    total_other_income_expenses_net REAL,
    net_income_from_continuing_operations REAL,
    other_adjustments_to_net_income REAL,
    net_income_deductions REAL,

    PRIMARY KEY (symbol, date, reported_currency),
    FOREIGN KEY (symbol) REFERENCES stocks(symbol)
);
