-- Income statement growth
CREATE TABLE income_statement_growth (
    symbol TEXT,
    date TEXT,
    fiscal_year TEXT,
    period TEXT,
    reported_currency TEXT,

    growth_revenue REAL,
    growth_cost_of_revenue REAL,
    growth_gross_profit REAL,
    growth_gross_profit_ratio REAL,
    growth_research_and_development_expenses REAL,
    growth_general_and_administrative_expenses REAL,
    growth_selling_and_marketing_expenses REAL,
    growth_other_expenses REAL,
    growth_operating_expenses REAL,
    growth_cost_and_expenses REAL,
    growth_interest_income REAL,
    growth_interest_expense REAL,
    growth_depreciation_and_amortization REAL,
    growth_ebitda REAL,
    growth_operating_income REAL,
    growth_income_before_tax REAL,
    growth_income_tax_expense REAL,
    growth_net_income REAL,
    growth_eps REAL,
    growth_eps_diluted REAL,
    growth_weighted_average_shs_out REAL,
    growth_weighted_average_shs_out_dil REAL,
    growth_ebit REAL,
    growth_non_operating_income_excluding_interest REAL,
    growth_net_interest_income REAL,
    growth_total_other_income_expenses_net REAL,
    growth_net_income_from_continuing_operations REAL,
    growth_other_adjustments_to_net_income REAL,
    growth_net_income_deductions REAL,

    PRIMARY KEY (symbol, date),
    FOREIGN KEY (symbol) REFERENCES stocks(symbol)
);
