mode: "ml"
model_path: "models/value_model.pkl"

features:
  - z_inverse_pe
  - z_inverse_pb
  - z_dcf_discount

# Used if mode == "statistical"
weights:
  z_inverse_pe: 0.5
  z_inverse_pb: 0.3
  z_dcf_discount: 0.2
