factors:
  value:
    mode: "ml"
    model_config:
      type: "random_forest"
      hyperparameters:
        n_estimators: 100
        max_depth: 4
      features: ["peRatio", "pbRatio", "dcf", "price"]
      model_path: "models/value_rf.pkl"

fetchers:
  value:
    default_start_date: "2020-01-01"
    default_end_date: "2024-12-31"
    clean_missing: true
    frequency: "M"