factors:
  value:
    mode: "ml"
    model_config:
      type: "random_forest"
      hyperparameters:
        n_estimators: 100
        max_depth: 4
      features: ["peRatio", "pbRatio", "dcf", "price"]
      model_path: "models/value_rf.pkl"
