-- Key metrics
CREATE TABLE IF NOT EXISTS key_metrics (
    symbol TEXT,
    date TEXT,
    fiscal_year TEXT,
    period TEXT,
    reported_currency TEXT,
    market_cap REAL,
    enterprise_value REAL,
    ev_to_sales REAL,
    ev_to_operating_cash_flow REAL,
    ev_to_free_cash_flow REAL,
    ev_to_ebitda REAL,
    net_debt_to_ebitda REAL,
    current_ratio REAL,
    income_quality REAL,
    graham_number REAL,
    graham_net_net REAL,
    tax_burden REAL,
    interest_burden REAL,
    working_capital REAL,
    invested_capital REAL,
    return_on_assets REAL,
    operating_return_on_assets REAL,
    return_on_tangible_assets REAL,
    return_on_equity REAL,
    return_on_invested_capital REAL,
    return_on_capital_employed REAL,
    earnings_yield REAL,
    free_cash_flow_yield REAL,
    capex_to_operating_cash_flow REAL,
    capex_to_depreciation REAL,
    capex_to_revenue REAL,
    sga_to_revenue REAL,
    rnd_to_revenue REAL,
    sbc_to_revenue REAL,
    intangibles_to_total_assets REAL,
    average_receivables REAL,
    average_payables REAL,
    average_inventory REAL,
    dso REAL,
    dpo REAL,
    dio REAL,
    operating_cycle REAL,
    cash_conversion_cycle REAL,
    fcf_to_equity REAL,
    fcf_to_firm REAL,
    tangible_asset_value REAL,
    net_current_asset_value REAL,
    PRIMARY KEY (symbol, date),
    FOREIGN KEY (symbol) REFERENCES stocks(symbol)
);